chore: add jest and github action
visionect/posthog-plugin-snowplow-referer-parser pull request #1
Opened 2023-06-29 09:19 UTC by hazzadous

We need to be able to ensure that the functionality is correct so we
make it possible to run `yarn jest` to validate.

2023-07-17 13:47 UTC, Burzo requested changes

2023-07-17 13:47 UTC, Burzo commented on index.test.ts
> +import { processEvent } from ".";
Please use prettier with the provided `.prettierrc` config file and format the file.

2023-07-17 13:47 UTC, Burzo commented on jest.config.js
> +module.exports = {
Same as `index.test.js` file above, please use `prettier` to format it.

2023-07-17 13:47 UTC, Burzo commented on jest.config.js
> +            // Without isolatedModules, tests run realy slow, so we enable them
Nitpick: typo (`realy` -> `really`)

2023-07-17 13:48 UTC, Burzo commented
Also, there is a deprecation warning when running tests:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
which should be solvable by following the instructions in the warning.

2023-07-17 13:54 UTC, Burzo requested changes
There is also a deprecation warning reported by Jest which should be solvable by following the instructions in the warning itself:

```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

2023-07-17 13:55 UTC, Burzo commented
And also, hey @hazzadous! Hopefully, you didn't have to wait too long for us to take a look at this, and thanks for your help so far.

2023-08-17 08:10 UTC, merged

2023-08-17 10:21 UTC, hazzadous commented
Hi @Burzo hope you get this working! I believe Xavier or Tiina at PostHog are the best to reference on any followups 🙏